### ISSUE TITLE
annotate compounds

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/update-content-registry#16]
update aug 12

annotations to add 
- [x] LINCS
- [x] PubChem
- [x] Glycan
- [x] DrugCentral

see #46 and #33 

---

I'd like to add some external links for the compounds but the ID field is interesting... because the ID is numeric for PUBMed but a strong for GlyTouCan

https://github.com/nih-cfde/published-documentation/wiki/TableInfo:-compound.tsv

![Screen Shot 2022-06-30 at 2 05 05 PM](https://user-images.githubusercontent.com/7544197/176779148-e8d22417-4de5-4233-ada6-2f1df92fc607.png)

![Screen Shot 2022-06-30 at 2 18 32 PM](https://user-images.githubusercontent.com/7544197/176780030-130cef72-3e6e-4c5f-84e6-3f212292548b.png)

So, we would need like an if/else statement to send the {ID} to either https://glytoucan.org/Structures/Glycans/{ID}  or https://pubchem.ncbi.nlm.nih.gov/compound/{ID} as appropriate

![Screen Shot 2022-06-30 at 2 16 19 PM](https://user-images.githubusercontent.com/7544197/176779681-bdfc0635-afd4-48e6-8fa6-a8a24db568e7.png)

![Screen Shot 2022-06-30 at 2 14 34 PM](https://user-images.githubusercontent.com/7544197/176779575-665e4855-ddb2-4b65-a50c-1311292c67a8.png)

**Comment by ctb** [comment]
that shouldn't be a problem! Let me know if you need some help with the Python - e.g.,

```
try:
    cv_id = int(cv_id)
    # do things with it as an integer!
except ValueError:
   # can't be converted! it's a string!
   # do things with it as an integer
```

should work. You could also do more complicated things with a regular expression but from looking at the above, it should work.

An alternative would be to use the leading 'G' in GlyTouCan IDs, if they are indeed always there:

```
if cv_id.startswith('G'):
   # do glytoucan stuff
else:
   # do pubchem stuff
```

**Comment by jeremyjyang** [comment]
Hi, I'm trying to add compound data too. It seems we need [compound.tsv](https://github.com/nih-cfde/update-content-registry/blob/main/data/validate/compound.tsv) to be populated. For all PubChem compounds this is a large file [compounds.tsv.gz](https://osf.io/bq6k9/files/osfstorage/62473e83746f5900534a64b4) is 2.3GB. As an alternate solution or workaround, I could add only those compounds needed. Advice or comments?

**Comment by raynamharris** [comment]
Thanks @jeremyjyang. 

See https://github.com/nih-cfde/update-content-registry/pull/33. The gunziped OSF file was about 14 GB in size, so I made a small version that contains info for about 4000 compounds, all of which are associated with files in the portal. 

Let me know if that file contains all the compounds you are trying to annotate or not. Thanks!

**Comment by raynamharris** [comment]
Notes
* none of the compounds in the portal with files associated were listed by GlyTouCan, so I didn't have to use any if/else statements. 
* currently i can't login to the VPN, so I haven't updated staging, but its working locally.
Also

**Comment by raynamharris** [comment]
also add images, like  

![image](https://user-images.githubusercontent.com/7544197/183475999-06b8b297-b7ce-49c3-9baf-faf53f33ad91.png)

with

`![Image](https://api.glygen.org/glycan/image/G17689DH)`

`![Image](https://api.glygen.org/glycan/image/{cv_id})`

**Comment by raynamharris** [comment]
Added a link to glygan and displayed the image for 24,038 glycans that have pages in staging.  commit https://github.com/nih-cfde/update-content-registry/pull/33/commits/fb1341213c467095751ffdac7efbcf9b897ff876


markdown content added:

External links: More information is available on GlyGen website for glycan [G99997WS](https://www.glygen.org/glycan/G99997WS).


preview:

![Screen Shot 2022-08-08 at 11 07 51 AM](https://user-images.githubusercontent.com/7544197/183485000-db8cbba5-f268-4c97-9303-b7502878d489.png)

**Comment by raynamharris** [comment]
have glycan images for compounds referred to by pubchem id too now :)

![Screen Shot 2022-08-09 at 4 49 11 PM](https://user-images.githubusercontent.com/7544197/183781196-53017090-fe1b-4eb8-89df-fea5d8d88ccd.png)

**Comment by raynamharris** [comment]
I've also added Drug Central. I’m currently working with two conversion tables, one for glycan id and one for drug central. i’m going to combine those and combine the python scripts and then i’ll make a simple table with all the different links and images below. see https://github.com/nih-cfde/knowledge-base-deposit/pull/3 and https://github.com/nih-cfde/update-content-registry/pull/33/commits/e6ccc38cc17386a379d29c0135bdcd8b209fb51c

![Screen Shot 2022-08-11 at 11 07 02 AM](https://user-images.githubusercontent.com/7544197/184209602-de485ded-62cb-4526-98ba-b17476cf38f9.png)

**Comment by raynamharris** [comment]
now using 4 scripts each with different input list to annotate with pubchem, lincs, drug central, and glycan information and images. See PR https://github.com/nih-cfde/update-content-registry/pull/33. cc @jeremyjyang @u8sand @ReneRanzinger

**glycan only**
![Screen Shot 2022-08-12 at 1 51 07 AM](https://user-images.githubusercontent.com/7544197/184320484-82cd0594-d1f2-4fa0-9613-3f850a08675b.png)

**pub chem and glycan**
![Screen Shot 2022-08-12 at 1 48 35 AM](https://user-images.githubusercontent.com/7544197/184320493-5a86bb56-6489-4f2d-a34d-137d4f9e83b2.png)


**pub chem and lincs**
![Screen Shot 2022-08-12 at 1 49 04 AM](https://user-images.githubusercontent.com/7544197/184320498-e774b80d-d28b-471c-a3b5-cc45f12419bb.png)


**drug and pub chem**
![Screen Shot 2022-08-12 at 1 48 49 AM](https://user-images.githubusercontent.com/7544197/184320495-1f8eb232-b3ad-494b-b404-51c6ddf37f6d.png)
