### ISSUE TITLE
annotate anantomy pages

### ISSUE THREAD

**Issue by jessicalumian** [nih-cfde/update-content-registry#26]
Rayna/we know how to make the link from genes to URL, but we want to figure this out for anatomy (and variants)

All we need is a link to this C2M2 term to external issues

Could also add in line images, etc.

**Comment by raynamharris** [comment]
I would like to add an external link to the EMBL-EBI Ontology Lookup Service

The input list uses semi colon: e.g. UBERON:0000007
But URL uses an underscore: e.g http://purl.obolibrary.org/obo/UBERON_0000007

I'm not sure what python commands to use to substitute : for _ to make a new script for a new rule

**Comment by ctb** [comment]
```
new_uberon_id = uberon_id.replace(':', '_')
```
maybe?

**Comment by raynamharris** [comment]
Yes! That worked. See #32 

External links: Use the Ontology Lookup Service (OLS) from EMBL-EBI to learn more about [UBERON:0001911](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001911).

![Screen Shot 2022-07-22 at 11 21 55 AM](https://user-images.githubusercontent.com/7544197/180501287-55ac2420-c399-487f-8cd5-2ec1f24d7f68.png)

**Comment by raynamharris** [comment]
workflow 

1.  connect to AWS VPN client
2. login 
3. edit files
4. make resources
5. refresh resources

```
python3 -m cfde_deriva.cfde_login login app.nih-cfde.org 

make clean
make
make update

python3 -m cfde_deriva.release refresh-resources f1da20a5-24c1-418e-9707-371702f3987e
```
