### ISSUE TITLE
add GTEx widget pages to all genes for which GTEx has information

### ISSUE THREAD

**Issue by ctb** [nih-cfde/update-content-registry#54]
right now the GTEx widget page is only on ~10 genes; we should expand this.

we need to get a list of genes from GTEx.

**Comment by raynamharris** [comment]
I created a list of genes from GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz from https://gtexportal.org/home/datasets and used it to annotate 19352 gene pages. See recent commits in #60
