### ISSUE TITLE
Invalid IDs in input list of PRs

### ISSUE THREAD

**Issue by u8sand** [nih-cfde/update-content-registry#65]
It was brought to my attention that this link: https://maayanlab.cloud/gene-kg?start=Cell+or+Tissue+%28HuBMAP%29&start_field=id&start_term=UBERON_0000007 was invalid.

But this ID is not in our KG -- the original PR does not include this ID;
https://github.com/nih-cfde/update-content-registry/blob/3db5e3c25f5f8d8a5d1b0eb1a7031ef3c5b1c0a9/data/inputs/anatomy_IDs_for_gene_kg.txt

However the merged commit does:
https://github.com/nih-cfde/update-content-registry/commit/3dcd1db56c46618e88504a40f9695bfa50b49e8e#diff-c362f762c20e85f51c319ece8249ada14a19acfe8cb3fe0c9d541d8bc1067dd3R19

Please fix the input lists or regenerate them with the scripts used to generate them to begin with (https://github.com/nih-cfde/update-content-registry/blob/main/scripts/build-markdown-pieces-gene-kg.py#L32-L35).

**Comment by raynamharris** [comment]
Thanks @u8sand. I accidentally added that ID during testing. I created PR #66 have updated the portal, so the invalid widget is not longer present. See https://app.nih-cfde.org/chaise/record/#1/CFDE:anatomy/nid=172
